#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

#do_one inlist_to_zams_header zams.mod LOGS_zams
#do_one inlist_to_end_core_h_burn_header tams.mod
#do_one inlist_to_end_core_he_burn_header after_he_burn.mod 
do_one inlist_to_end_core_c_burn_header after_c_burn.mod


date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'
